apps/board/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, SubmitField
from wtforms.validators import Length, DataRequired

# 부서 선택? 직장인, 취준생
class BoardForm(FlaskForm):
  subject = StringField(
    "제목",
    validators=[
      DataRequired(message="제목은 필수 입력해주세요."),
      Length(min=3, max=50, message="3자 이상 50자 이내로 작성해주세요.")
    ]
  )

  content = TextAreaField(
    "내용",
    validators=[
      DataRequired(message="내용은 필수 입력해주세요.")
    ],
    render_kw={'rows':10}
  )

  submit = SubmitField('등록')

apps/board/views.py
from flask import Blueprint, render_template, redirect, url_for, request, jsonify, flash, session
from flask_login import login_required, current_user
from apps.board.forms import BoardForm
from apps.crud.models import Board, Recommend, Comment, UserRole
from apps.app import db


board = Blueprint('board', __name__, template_folder='templates', static_folder='static')

@board.route("/<int:selection>", methods=["GET"])
@login_required
def index(selection):
    if not current_user.is_authenticated:
      return redirect(url_for('auth.login', next=request.url))  # 로그인 페이지로 이동 및 next에 현재 URL 저장
    
    department_id = request.args.get("department_id")

    if selection == 1 and current_user.userinfo.department_id == 99:
        return render_template("board/permission_denied.html")

    # 필터링 처리
    if department_id and int(department_id) != 0:
        query = Board.query.filter(Board.department_id == department_id, Board.selection == 1).order_by(Board.id.desc())
    else:
        if selection == 1:
            query = Board.query.filter(Board.selection == 1).order_by(Board.id.desc())
        elif selection == 2:
            query = Board.query.filter(Board.selection == 2).order_by(Board.id.desc())
        else:
            query = Board.query.filter(Board.selection == 3).order_by(Board.id.desc())


    # 최신 게시글 2개에 'is_new' 설정
    boards = query.all()  # 쿼리 객체로 유지하면서 all() 호출
    # 컬럼 총 개수
    board_total = query.count()

    for idx, board in enumerate(boards):
        board.is_new = idx < 2  # 상위 2개 게시글만 is_new=True

    # 페이징 처리
    page = request.args.get('page', type=int, default=1)
    boards = query.paginate(page=page, per_page=10)  # paginate() 호출

    block_size = 10
    current_block = (page - 1)//block_size + 1

    start_page = (current_block - 1)*block_size + 1
    end_page = min(current_block*block_size, boards.pages)

    has_prev_block = start_page > 1
    has_next_block = end_page < boards.pages

    page_start_number = board_total - (page - 1) * 10
    
    pagination = {
      "current_block" : current_block,
      "start_page" : start_page,
      "end_page" : end_page,
      "has_prev_block" : has_prev_block,
      "has_next_block" : has_next_block,
      "page_start_number": page_start_number,
    }

    return render_template("board/index.html", boards=boards.items, selection=selection, pagination=pagination, page=page)
  
@board.route("/new", methods=["GET", "POST"])
@login_required
def new():
  form = BoardForm() 

  if form.validate_on_submit():
    board = Board(
      selection = request.form.get("board_type"),
      subject = form.subject.data,
      content = form.content.data,
      user = current_user,
      department_id = current_user.userinfo.department_id
    )


    db.session.add(board)
    db.session.commit()
    return redirect(url_for("board.index", selection=board.selection))

  return render_template("board/new.html", form=form, user=current_user)

@board.route("/detail/<int:board_id>", methods=["GET", "POST"])
@login_required
def detail(board_id):
  if not current_user.is_authenticated:
      return redirect(url_for('auth.login', next=request.url))  # 로그인 페이지로 이동 및 next에 현재 URL 저장

  keyword = request.args.get('keyword')
  board = Board.query.get_or_404(board_id)

  if current_user.role == UserRole.SEEKER:
    if board.selection == 1 :
     return render_template("board/permission_denied.html")


  view_key = f"viewed_{board_id}"
  if request.method == "GET":
     # 세션에서 해당 게시글을 조회했는지 확인
        if not session.get(view_key):
            board.increment_views()  # 조회수 증가
            session[view_key] = True  # 세션에 조회 기록 저장

  # 페이징 처리
  page = request.args.get('page', type=int, default=1)
  comments = Comment.query.filter_by(board_id=board.id).order_by(Comment.id.desc()).paginate(page=page, per_page=10)  # paginate() 호출

  block_size = 10
  current_block = (page - 1)//block_size + 1

  start_page = (current_block - 1)*block_size + 1
  end_page = min(current_block*block_size, comments.pages)

  has_prev_block = start_page > 1
  has_next_block = end_page < comments.pages
  
  pagination = {
    "current_block" : current_block,
    "start_page" : start_page,
    "end_page" : end_page,
    "has_prev_block" : has_prev_block,
    "has_next_block" : has_next_block
  }         

  return render_template("board/detail.html", board=board, comments=comments, pagination=pagination, page=page, keyword=keyword)


@board.route("/update/<int:board_id>", methods=["GET", "POST"])
@login_required
def update(board_id):
  board = Board.query.get_or_404(board_id)
  form = BoardForm()

  if form.validate_on_submit():
    board.subject = form.subject.data
    board.content = form.content.data

    db.session.add(board)
    db.session.commit()
    return redirect(url_for("board.detail", board_id=board_id))

  return render_template("board/update.html", board=board, form=form, user=current_user)



@board.route("/delete/<int:board_id>", methods=["DELETE"])
@login_required
def delete(board_id):
    Board.query.filter_by(id=board_id).delete()
    db.session.commit()


    return jsonify({"message": "게시물이 삭제되었습니다."}), 200


# 추천
@board.route("/recommend/<int:board_id>", methods=["POST"])
def recommend(board_id):
   recommend_entry = Recommend.query.filter_by(user_id=current_user.id, board_id=board_id).first()
   if recommend_entry:
      db.session.delete(recommend_entry)
      db.session.commit()
   else:
      new_recommend = Recommend(user_id=current_user.id, board_id=board_id)
      db.session.add(new_recommend)
      db.session.commit()
   return redirect(url_for("board.detail", board_id=board_id))

# 댓글
@board.route("/comment/new/<int:board_id>", methods=["POST"])
@login_required
def comment_new(board_id):
   board = Board.query.get_or_404(board_id)

   content = request.form.get("content") 

   if not content or content.strip() == "":
      flash("댓글 내용을 넣어 등록해 주세요", "error")
      return redirect(url_for("board.detail", board_id=board_id))

   comment = Comment(
      content = content,
      user = current_user,
      board = board
   )
   db.session.add(comment)
   db.session.commit()

   return redirect(url_for("board.detail", board_id=board_id))
  
@board.route("/comment/update/<int:comment_id>", methods=["PUT"])
def comment_update(comment_id):
   data = request.get_json()
   comment = Comment.query.get_or_404(comment_id)
   comment.content = data.get('content')

   db.session.add(comment)
   db.session.commit()

   return jsonify({"message": "댓글이 수정되었습니다."}), 200

@board.route("/comment/delete/<int:comment_id>", methods=["DELETE"])
def comment_delete(comment_id):
   Comment.query.filter_by(id=comment_id).delete()
   db.session.commit()
   return jsonify({"message":"댓글이 삭제 되었습니다."}), 200


# 더미 데이터 생성
@board.route('/dummy')
def make_dummy():
    create_boards_and_comments()  # Dummy 데이터 생성 함수 호출
    return "더미 데이터가 생성되었습니다."

# 더미 게시글 및 댓글 생성 함수
def create_boards_and_comments():
    users = [(4, 50), (3, 50)]
    
    for user_id, start_index in users:
        for i in range(50):
            board = Board(
                subject=f'임시제목{start_index + i}',
                content=f'임시내용{start_index + i}',
                user_id=user_id,
                selection=1,
                department_id=user_id
            )
            db.session.add(board)

    db.session.commit()  # 한 번에 커밋

    # 댓글 생성
    for i in range(50):
        comment = Comment(
            content=f'임시내용{i+50}',
            user_id=3,
            board_id=200
        )
        db.session.add(comment)

    db.session.commit()  # 한 번에 커밋

apps/board/templates/board/detail.html
{% extends "base.html" %}
{% block title %}게시물상세보기{% endblock %}

{% block css %}
<link rel="stylesheet" href="{{url_for('board.static', filename='css/detail.css')}}">
{% endblock %}

{% block content %}
<div class="board-detail">
  <div>
    <label>제목</label>
    <input type="text" value="{{board.subject}}" readonly>
  </div>
  <div>
    <label>작성자</label>
    <input type="text" value="{{board.user.username}}" readonly>
  </div>
  <div>
    <label>작성일자</label>
      <input type="text" value="{{board.created_at}}" readonly>
    </div>
    <div>
      <label>내용</label>
      <textarea rows="10" readonly>{{board.content}}</textarea>
    </div>
    <div>
      <form action="{{url_for('board.recommend', board_id=board.id)}}" method="post" class="recommend-form">
        <input type="hidden" name="csrf_token" value="{{csrf_token()}}">
        <button type="submit" class="thumbs-up-button {% if current_user in board.recommender %}active-btn{% endif %}">
          ❤️
          추천
        </button>
      </form>      
      <p>추천 수 : {{ board.recommender | length }}</p>
    </div>
    <div class="board-detail-btns">
      <!-- 글 수정 -->
      <div class="board-update-btn">
        {% if current_user.id == board.user.id %}
        <a href="{{url_for('board.update', board_id=board.id)}}" class="btn btn-warning">수정</a>
        {% else %}
        <button class="btn btn-warning" disabled>수정</button>
        {% endif %}
      </div>
      <!-- 글 삭제 -->
      <div class="board-delete-btn">
          <!-- 토큰 -->
          <input type="hidden" name="csrf_token" value="{{csrf_token()}}">
          {% if current_user.id == board.user.id %}
          <input class="btn btn-danger board-delete" type="submit" data-board-id="{{board.id}}" data-board-selection="{{board.selection}}" value="삭제">
          {% else %}
          <input class="btn btn-danger board-delete" type="submit" data-board-id="{{board.id}}" data-board-selection="{{board.selection}}" value="삭제" disabled>
          {% endif %}
        </div>
      </div>
      <div class="board-detail-move">
        {% if keyword %}
          <a href="{{ url_for('search.search_keyword', keyword=keyword) }}" class="move-btn">목록</a>
        {% else %}
          {% if board.get_pre_board() %}
              <a href="{{ url_for('board.detail', board_id=board.get_pre_board().id) }}" class="move-btn">&lt;</a>
          {% else %}
              <span class="move-btn disabled">&lt;</span>
          {% endif %}       
          <a href="{{ url_for('board.index', selection=board.selection, board_id=board.id) }}" class="move-btn">목록</a> 
          {% if board.get_next_board() %}
              <a href="{{ url_for('board.detail', board_id=board.get_next_board().id) }}" class="move-btn">&gt;</a>
          {% else %}
              <span class="move-btn disabled">&gt;</span>
          {% endif %}
        {% endif %}  
      </div>   
    </div>
    <div class="comment-all">
      <div class="comment-new">
        <form action="{{url_for('board.comment_new', board_id=board.id)}}" method="post">
          <input type="hidden" name="csrf_token" value="{{csrf_token()}}">
          <input type="text" name="content" id="comment-content" placeholder="댓글을 입력해 주세요" data-board-id="{{board.id}}">
          <button id="comment-new-btn">등록</button>
        </form>
      </div>
      {% with messages = get_flashed_messages() %}
        {% for message in messages %}
          <p class="comment-msg">{{message}}</p>
        {% endfor %}
      {% endwith %}    
      <h5 class="comment-counts">댓글[{{board.comments|length}}]</h5>
      {% if board.comments %}
      <div class="comment-list">
        <div class="comment-header">        
          <div class="comment-header-item">내용</div>
          <div class="comment-header-item">작성자</div>
          <div class="comment-header-item">작성일자</div>
          <div class="comment-header-item"></div>
          <div class="comment-header-item"></div>
        </div>
        {% for comment in comments %}
        <div class="comment-items">
          {% if current_user.id == comment.user.id %}
            <div class="comment-item comment-content-show">{{comment.content}}</div>
            <!-- 토큰 -->
            <input type="hidden" name="csrf_token" value="{{csrf_token()}}">
            <input class="new-content" type="text" name="new-content" 
            data-comment-id="{{comment.id}}" value="{{comment.content}}" style="display: none;">
          {% else %}
            <div class="comment-item comment-content-show">{{comment.content}}</div>
          {% endif %}
          <div class="comment-item comment-user-show">{{comment.user.username}}</div>
          <div class="comment-item comment-date-show">{{comment.created_at}}</div>

          <!-- 댓글작성자가 수정 누르면 저장, 삭제 버튼 보임 -->
          {% if current_user.id == comment.user.id %}
            <div class="comment-item">
              <button class="comment-update-btn" data-comment-id="{{comment.id}}">수정</button>
              <button class="comment-save-btn" data-comment-id="{{comment.id}}" style="display: none;">저장</button>
            </div>
            <div class="comment-item">
              <button class="comment-delete-btn" data-comment-id="{{comment.id}}" style="display: none;">삭제</button>
            </div>
          {% endif %}
        </div>
        {% endfor %}
      </div>
      {% else %}
      <p> 댓글이 없습니다. 댓글을 등록해 주세요.</p>
      {% endif %}

      {% set current_page = page or 1 %}
      <div class="pagination">
        {% if pagination.has_prev_block %}
        <li>
          <a href="{{ url_for('board.detail', board_id=board.id, page=pagination.start_page - 1) }}">&lt;&lt;</a>
        </li>
        {% endif %}
        {% for num in range(pagination.start_page, pagination.end_page + 1) %}
        <li>
          <a href="{{ url_for('board.detail',  board_id=board.id, page=num) }}" 
          class="page-link {% if current_page == num|int %}active-page{% endif %}">
          {{ num }}
          </a>
        </li>
        {% endfor %}
        {% if pagination.has_next_block %}
        <li>
          <a href="{{ url_for('board.detail', board_id=board.id, page=pagination.end_page + 1) }}">&gt;&gt;</a>
        </li>
        {% endif %}
      </div>
  </div>
{% endblock %}

{% block js %}
  <script src="{{url_for('board.static', filename='js/detail.js')}}"></script>
{% endblock %} 

apps/board/templates/board/index.html
{% extends "base.html" %}
{% block title %} 게시물 {%endblock%}
{% block css %}
<link rel="stylesheet" href="{{url_for('board.static', filename='css/index.css')}}">
{% endblock %}

{% block content %}

<div class="board-index-top">
  <div class="board-selection">
    {% if selection == 1 %}
      <h3>직장인 게시판</h3>
    {% elif selection == 2%}
      <h3>구직자 게시판</h3>
    {% else %}
      <h3>모두 게시판</h3>
    {% endif %}
  </div>

  <div class="board-index-company">
    {% if selection == 1 %}
     <form action="{{url_for('board.index', selection=1)}}" method="get">
      <select name="department_id" class="form-select" aria-label="Default select example" onchange="this.form.submit()">
         <option value="0" selected>부서를 선택해주세요</option>
         <option value="1">대한통운</option>
         <option value="2">제일제당</option>
         <option value="3">프레시웨이</option>
         <option value="4">ENM</option>
         <option value="5">CGV</option>
         <option value="6">스튜디오드래곤</option>
         <option value="7">CJ 씨푸드</option>
         <option value="8">CJ 바이오사이언스</option>
       </select>
     </form>
    {% endif %}
     <a href="{{url_for('board.new')}}" class="btn btn-secondary">게시물 등록</a>
  </div>
</div>

<div class="board-list">
  <a href="{{url_for('board.index', selection=1)}}">직장인게시판</a>
  <a href="{{url_for('board.index', selection=2)}}">구직자게시판</a>
  <a href="{{url_for('board.index', selection=3)}}">모두게시판</a>
</div>

{% if boards %}
<div class="board-index-content">
  <div class="board-header">
    <div class="board-header-item">번호</div>
    <div class="board-header-item">제목</div>
    <div class="board-header-item">작성자</div>
    <div class="board-header-item">작성일시</div>
    <div class="board-header-item">추천</div>
    <div class="board-header-item">조회수</div>
  </div>
  
  {% for board in boards %}
  <div class="board-row">
    <div class="board-item">
      {{ pagination.page_start_number - loop.index0 }}
    </div>
    <div class="board-item">
      <a href="{{ url_for('board.detail', board_id=board.id) }}">{{ board.subject }}</a>
      {% if board.is_new %}
      <span class="label label-new">NEW</span>
      {% endif %}
    </div>
    <div class="board-item">{{ board.user.username }}</div>
    <div class="board-item">{{ board.created_at }}</div>
    <div class="board-item">{{ board.recommender|length }}</div>
    <div class="board-item">{{ board.views }}</div>
  </div>
  {% endfor %}
  
{% else %}
  <p class="board-none">등록된 게시글이 없습니다. 등록해 주세요</p>
{% endif %}
</div>


<div class="pagination">
  {% if pagination.has_prev_block %}
  <li>
    <a href="{{ url_for('board.index', selection=selection, department_id=request.args.get('department_id'), page=pagination.start_page - 1) }}">&lt;&lt;</a>
  </li>
  {% endif %}
  {% for num in range(pagination.start_page, pagination.end_page + 1) %}
  <li>
    <a href="{{ url_for('board.index', selection=selection, department_id=request.args.get('department_id'), page=num) }}" 
    class="page-link {% if page == num %}active-page{% endif %}">
    {{ num }}
    </a>
  </li>
  {% endfor %}
  {% if pagination.has_next_block %}
  <li>
    <a href="{{ url_for('board.index', selection=selection, department_id=request.args.get('department_id'), page=pagination.end_page + 1) }}">&gt;&gt;</a>
  </li>
  {% endif %}
</div>


{% endblock %}

{% block js%}
<script src="{{url_for('board.static', filename='js/index.js')}}"></script>
{% endblock %}

apps/board/templates/board/new.html
{% extends "base.html" %}
{% block title %}게시물 등록{% endblock %}

{% block css %}
<link rel="stylesheet" href="{{ url_for('board.static', filename='css/new.css') }}">
{% endblock %}

{% block content %}
<div class="new-board">
  <form action="{{ url_for('board.new') }}" method="post">
    {{ form.csrf_token }}
    
    <div>
      <p>게시판 선택</p>
      {% if user.role.value == 'seeker' %}
      <select class="board-select" name="board_type" aria-label="게시판 선택">
        <option value="2">구직자 게시판</option>
        <option value="3">전체 게시판</option>
      </select>
      {% else %}
      <select class="board-select" name="board_type" aria-label="게시판 선택">
        <option value="1">직장인 게시판</option>
        <option value="2">구직자 게시판</option>
        <option value="3">전체 게시판</option>
      </select>
      {% endif %}
    </div>

    <div>
      {{ form.subject.label }}
      {{ form.subject(class_="form-control", placeholder="제목을 입력하세요") }}
      {% for error in form.subject.errors %}
        <p style="color: red;">{{ error }}</p>
      {% endfor %}
    </div>

    <div>
      {{ form.content.label }}
      {{ form.content(class_="form-control", placeholder="내용을 입력하세요") }}
      {% for error in form.content.errors %}
        <p style="color: red;">{{ error }}</p>
      {% endfor %}
    </div>

    <div>
      {{ form.submit(class_="btn btn-primary") }}
    </div>
  </form>
</div>
{% endblock %}

{% block js %}

{% endblock %}

apps/board/templates/board/permission_denied.html
{% extends "base.html" %}

{% block title %}권한 없음{% endblock %}

{% block content %}
  <h2>권한이 없습니다.</h2>
  <p>이 페이지에 접근할 권한이 없습니다. 관리자에게 문의하십시오.</p>
  
  <a href="/" class="btn btn-primary">홈으로 돌아가기</a>
  <a href="javascript:history.back()" class="btn btn-secondary">이전으로 돌아가기</a>
{% endblock %}

apps/board/templates/board/update.html
{% extends "base.html" %}
{% block title %}게시물 수정{% endblock %}

{% block css %}
<link rel="stylesheet" href="{{url_for('board.static', filename='css/new.css')}}">
{% endblock %}

{% block content %}
<div class="board-update">
  <form action="{{ url_for('board.update', board_id=board.id) }}" method="POST">
    {{form.csrf_token}}
    <div>
      <p>게시판 선택</p>
      {% if user.role.value == 'seeker' %}
      <select class="board-select" name="board_type" aria-label="게시판 선택" disabled>
        <option value="2">구직자 게시판</option>
        <option value="3">모두 게시판</option>
      </select>
      {% else %}
      <select class="board-select" name="board_type" aria-label="게시판 선택" disabled>
        <option value="1">직장인 게시판</option>
        <option value="2">구직자 게시판</option>
        <option value="3">모두 게시판</option>
      </select>
      {% endif %}
    </div>
    <div>
      {{ form.subject.label }}
      {{ form.subject(class_="form-control", value=board.subject) }}
      {% for error in form.subject.errors %}
        <p style="color: red;">{{ error }}</p>
      {% endfor %}
    </div>
    <div>
      {{form.content.label}}
      <textarea name="{{ form.content.name }}" class="large-textarea">{{ board.content }}</textarea>
      {% for error in form.content.errors %}
        <p style="color: red;">{{error}}</p>
      {% endfor %}  
    </div>
    <div>
      {{form.submit(class='btn btn-primary')}}    </div>
  </form>
</div>
{% endblock %}

{% block js %}

{% endblock %}